# Generated by Django 4.0.5 on 2023-06-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_whatsapp_device_groups_whatsapp_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapp',
            name='device_groups',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='user',
        ),
    ]
