# Generated by Django 4.0.5 on 2023-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0006_whatsapp_user"),
        ("MessageStore", "0044_device_sms_alter_device_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="whatsapps",
            field=models.ManyToManyField(
                blank=True,
                related_name="devices",
                to="webhooks.whatsapp",
                verbose_name="WhatsApp Users",
            ),
        ),
        migrations.AlterField(
            model_name="devicegroup",
            name="whatsapps",
            field=models.ManyToManyField(
                blank=True,
                related_name="device_groups",
                to="webhooks.whatsapp",
                verbose_name="WhatsApp User",
            ),
        ),
    ]
