# Generated by Django 4.0.5 on 2023-03-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0045_alter_device_whatsapps_alter_devicegroup_whatsapps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='MessageStore.device'),
        ),
    ]
