# Generated by Django 4.0.5 on 2023-05-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageStore', '0046_alter_data_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='whatsapps',
        ),
        migrations.RemoveField(
            model_name='devicegroup',
            name='whatsapps',
        ),
    ]
