# Generated by Django 4.0.5 on 2023-06-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_remove_whatsapp_device_groups_and_more'),
        ('MessageStore', '0047_remove_device_whatsapps_remove_devicegroup_whatsapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='whatsapps',
            field=models.ManyToManyField(blank=True, to='webhooks.whatsapp', verbose_name='WhatsApp Users'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='whatsapps',
            field=models.ManyToManyField(blank=True, to='webhooks.whatsapp', verbose_name='WhatsApp User'),
        ),
        migrations.AlterField(
            model_name='data',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageStore.device'),
        ),
    ]
